### ISSUE TITLE
Обращение

### ISSUE THREAD

**Issue by varfomoleev** [developerivanov/ServerStatusBySMS#1]
Привет, никак не могу достучаться до тебя. Мне не нравится работа тех. поддержки, пожалуйста отпиши мне в вк vk.com/mxm_mnm

**Comment by varfomoleev** [comment]
![Uploading Screenshot_2021-07-14-10-18-16-678_com.android.chrome.jpg…]()

**Comment by varfomoleev** [comment]
![Screenshot_2021-07-14-10-18-22-879_com android chrome](https://user-images.githubusercontent.com/87407026/125560543-b54bd15a-18e0-418b-b66e-e76c5d128229.jpg)

**Comment by varfomoleev** [comment]
![Screenshot_2021-07-14-10-18-16-678_com android chrome](https://user-images.githubusercontent.com/87407026/125560589-55ee3ecd-21a3-4590-82a2-b254c524535e.jpg)

**Comment by developerivanov** [comment]
Не стоило сюда писать об этом... На сервере действительно было такое правило, но оно куда-то пропало... Я уже передал технической поддержке просьбу о том, чтобы вас разблокировали.
